# config/database.yml

default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: DavidJr@123
  host: localhost

development:
  <<: *default
  database: toyapp_development

test:
  <<: *default
  database: toyapp_test

production:
  <<: *default
  database: toyapp_production
  username: toyapp
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
